### PR TITLE
only set trial_duration if doing a timed trial

### PR DESCRIPTION
**Pull request by digitalmoksha**
We shouldn't set the trial_duration unless we're actually doing a timed trial.  This allows the possibility to have an open ended trial (like a beta for example).

### CODE REVIEW

**Comment by henderea** [comment]
Merged.  Good to know someone other than me uses this gem :)

**Comment by digitalmoksha** [comment]
Yeah, it's a nice little gem.  I'm working on another PR, that depending the setting of an environment variable, will pull in the either the Paddle or Paddle-MAS framework.  Basically it will be

```
  if ENV.fetch('store', 'paddle').downcase == 'paddle'
    app.pods.pod 'Paddle', git: 'https://github.com/PaddleHQ/Mac-Framework.git'
  elsif ENV.fetch('store', 'paddle').downcase == 'mas'
    app.pods.pod 'Paddle-MAS', git: 'https://github.com/PaddleHQ/Paddle-MAS.git'
  end
```

and a few changes to the `setup` method.

**Comment by henderea** [comment]
Thanks for helping.  I've kind of put the project I use this gem for on the back-burner, so I haven't been updating this gem as much either.  There are also other new things that I have yet to add support for, such as analytics, so if you use any of those things, maybe you could help add them in.  I'll typically respond to pull requests fairly quickly, but I haven't been putting much time into doing my own development on this gem.

I still pretty much just use the basic Paddle functionality in my app (which hasn't earned enough to be worth spending money on special options like advanced analytics), so adding in support for the new parts of the framework is not necessarily all that high on my list.  It's a relatively simple gem to add features to, so I don't think it's all that hard for people to help out with it, and I'm happy to merge any pull requests that come up.  However, while I will look at the changes in a pull request, I won't necessarily test them, so it will help if you can test them yourself before making the pull request.

Anyway, thanks for helping out with improving this gem.

**Comment by digitalmoksha** [comment]
I haven't decided if I'm going to use the advanced stuff yet.  But since I want to be in both the Mac App Store and the Paddle store, making that possible is the next thing on my list.  If start using those things, i'll look at adding them.

Thanks for the quick handling of the PR...

**Pull request merged**
