### PR TITLE
Enable mas

### PR DESCRIPTION
**Pull request by digitalmoksha**
use the `store` environment variable to link the framework for the Paddle store (`store=paddle`) or the Mac App Store (`store=mas`).  By default it will link in the Paddle store framework.

### CODE REVIEW

**Comment by henderea** [comment]
Merged, but with a bit of an improvement.  I added `mas_store?` and `paddle_store?` methods in the context used for the `app.paddle` block, so you don't have to check the environment variable yourself.

Check out the code changes and the updated readme.

**Comment by digitalmoksha** [comment]
ah cool, looks good...

**Comment by henderea** [comment]
Can you check out the changes I just committed?  I made it so that if you're only developing for the app store, you can pass a parameter to the `app.paddle` method that forces it to treat it as MAS.  Also, I made it so that the `store` parameter is automatically set when you call `app.paddle` (but before the block is executed)

**Comment by digitalmoksha** [comment]
yeah, i'll pull the changes locally and test in my environment and let you know

**Comment by digitalmoksha** [comment]
There seems to be a problem.  When I wrote this, I tried setting the app.paddle.store value directly from the environment variable, so that it wouldn't have to be included in the users Rakefile.  What happened is that it doesn't get set properly in the info_plist, because the short_version isn't available yet.  So what you get is:

```
"MotionPaddle_"                   => [
    {
      "store"       => "mas"
    }
  ],
"MotionPaddle_0.8"                => [
    {
      "trial_text"          => "Thank you for being a beta tester!",
      "current_price"       => "",
      "product_name"        => "Versatil Markdown",
     etc...
    }
  ],
```

So when I built using `rake store=mas`, in the app `MotionPaddle.store` returns `paddle`

**Comment by digitalmoksha** [comment]
This same problem is happening with the code you've added to set the `store` in `initialize`

**Comment by henderea** [comment]
Try what i just committed.  I think it should fix those issues.

**Comment by digitalmoksha** [comment]
Yep, that seemed to take care of it.  Much cleaner now.

**Pull request merged**
